#! /bin/bash

current_window_id=$(kitty @ ls | jq '.[] | .tabs[] | .windows[] | select(.is_active == true) | .id')

kitten @ launch /Users/zachdaniel/.dotfiles/priv_scripts/project hot-key $current_window_id 
