#! /bin/bash

current_window_id=$(kitty @ ls | jq '.[] | .tabs[] | .windows[] | select(.is_active == true) | .id')

if [[ $1 == "here" ]]; then
  kitten @ launch /Users/zachdaniel/.dotfiles/priv_scripts/project hot-key $current_window_id --here
else
  kitten @ launch /Users/zachdaniel/.dotfiles/priv_scripts/project hot-key $current_window_id 
fi

