# env

$env.config.buffer_editor = "nvim"

# Starship prompt (generated by env.nu)
source starship.nu

# mise (generated by env.nu)
source mise.nu

# Direnv
use std/config *

$env.config.hooks.env_change.PWD = $env.config.hooks.env_change.PWD? | default []

$env.config.hooks.env_change.PWD ++= [{||
    if (which direnv | is-empty) { return }

    direnv export json | from json | default {} | load-env
    $env.PATH = do (env-conversions).path.from_string $env.PATH
}]
