#!/usr/bin/env bash
direction="$1"
osascript -e '
tell application "Ghostty"
    perform action "goto_split:'"$direction"'" on focused terminal of selected tab of front window
end tell
' 2>/dev/null 1>/dev/null
