return {
  -- like it, but its not ready yet
  -- "A7Lavinraj/fyler.nvim",
  -- dependencies = { "echasnovski/mini.icons" },
  -- opts = {
  --   close_on_open = true,
  --   default_explorer = false,
  --   window_config = {
  --     width = 0.3,
  --     split = 'left',
  --   },
  --   window_options = {
  --     number = true,
  --     relativenumbers = true,
  --   },
  --   view_config = {
  --     git_status = {
  --       enable = true,
  --     },
  --   },
  -- },
  -- keys = {
  --   {
  --     "<leader>ft",
  --     function()
  --       require("fyler").show()
  --     end,
  --     desc = "Open fyler sidebar"
  --   }
  -- }
}
